source 'http://rubygems.org'

gem 'rails'
gem 'mysql'
gem 'serialport'
gem 'kramdown'
gem 'jquery-rails'
gem 'haml'
gem 'sass'
gem 'sass-rails'
gem 'rmagick'
#gem 'acts_as_list' #, '0.1.3'
#gem 'coffee-rails'
#gem 'uglifier'
#gem 'execjs'
#gem 'therubyracer'
#gem 'exception_notification', :require => 'exception_notifier'

group :test, :development do
#  gem 'rspec-rails'
#  gem 'factory_girl_rails'
#  gem 'capybara'
#  gem 'capybara-webkit'
#  gem 'launchy'
#  gem 'database_cleaner'
#  gem 'guard-rspec'
#  gem 'spork' #, '> 0.9.0.rc'
#  gem 'guard-spork'
#  gem 'ruby_core_source', '0.1.5'
  gem 'debugger'
end


