source 'http://rubygems.org'

# The following gems are already part of Debian Wheezy and do NOT cause a dependency to the online API of rubygems.org
gem 'rails', '4.1.8'
gem 'rake', '10.3.2'
gem 'rack', '1.5.2'
gem 'kramdown', '1.4.2'
gem 'jquery-rails', '3.1.2'
gem 'jquery-ui-rails', '4.2.0'
gem 'sass-rails', '4.0.3'
gem 'uglifier', '2.5.3'
gem 'serialport', '1.3.0'
gem 'haml', '4.0.5'
gem 'mysql2', '0.3.16'
gem 'coffee-rails', '4.0.1'

# The following gems are not part of Debian Jessie and DO cause a dependency to the online API of rubygems.org
 # jessies's version rmagick 2.13.2 seems to be broken

gem 'rmagick', '2.15.0'
gem 'therubyracer', :require => 'v8'
gem 'escper', '1.2.2'