source 'http://rubygems.org'

ruby '2.1.5'

gem 'rails', '4.1.8'
gem 'rake', '10.3.2'
gem 'rack', '1.5.2'
gem 'kramdown', '1.4.2'
gem 'jquery-rails', '3.1.2'
gem 'jquery-ui-rails', '4.2.0'
gem 'sass-rails', '4.0.3'
gem 'sprockets', '2.11.0'
gem 'uglifier', '2.5.3'
gem 'serialport', '1.3.0'
gem 'haml', '4.0.5'
gem 'mysql2', '0.3.16'
gem 'coffee-rails', '4.0.1'
gem 'rmagick', '2.15.0'

group :development do
  gem 'byebug'
end