#!/bin/sh

set -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_input high salor_hospitality/license_read || true
db_go
db_input high salor_hospitality/enter_database || true
db_go
db_input high salor_hospitality/enter_username || true
db_go
db_input high salor_hospitality/enter_password || true
db_go
