salor-hospitality/vendor/bundle   /var/lib/salor-hospitality/vendor
salor-hospitality/vendor/assets   /usr/share/salor-hospitality/vendor

salor-hospitality/app             /usr/share/salor-hospitality
salor-hospitality/config          /usr/share/salor-hospitality
salor-hospitality/lib             /usr/share/salor-hospitality
salor-hospitality/script          /usr/share/salor-hospitality

salor-hospitality/public/*.*      /usr/share/salor-hospitality/public
salor-hospitality/public/fonts    /usr/share/salor-hospitality/public
salor-hospitality/public/images   /usr/share/salor-hospitality/public

salor-hospitality/Gemfile*        /usr/share/salor-hospitality
salor-hospitality/Rakefile        /usr/share/salor-hospitality
salor-hospitality/config.ru       /usr/share/salor-hospitality

salor-hospitality/db/migrate        /usr/share/salor-hospitality/db
salor-hospitality/db/seeds.rb       /usr/share/salor-hospitality/db

salor-hospitality/db/schema.rb      /var/lib/salor-hospitality/db


config/salor-hospitality-http     /etc/apache2/sites-available
config/salor-hospitality-https    /etc/apache2/sites-available

config/salor-hospitality_browser-chromium         /usr/bin
config/salor-hospitality_console                  /usr/bin
config/salor-hospitality_exception-notification   /usr/bin
config/salor-hospitality_maintainance             /usr/bin
config/salor-hospitality_setup-https-access       /usr/bin
config/salor-hospitality_update                   /usr/bin
config/salor-hospitality_assets-precompile        /usr/bin

config/salor-hospitality_environment-vars.sh      /etc/profile.d

config/salor-hospitality-database.yml             /etc
salor-hospitality/config/database-production.default.yml /etc
config/salor-hospitality-config.yml               /etc

config/salor-hospitality.desktop               /usr/share/applications

salor-hospitality/app/assets/images/salor-hospitality-icon.svg          /usr/share/icons/hicolor/scalable/apps