Document: salor-hospitality
Title: Debian salor-hospitality Manual
Author: <insert document author here>
Abstract: This manual describes what salor-hospitality is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/salor-hospitality/salor-hospitality.sgml.gz

Format: postscript
Files: /usr/share/doc/salor-hospitality/salor-hospitality.ps.gz

Format: text
Files: /usr/share/doc/salor-hospitality/salor-hospitality.text.gz

Format: HTML
Index: /usr/share/doc/salor-hospitality/html/index.html
Files: /usr/share/doc/salor-hospitality/html/*.html
