#!/bin/bash

app_root=/usr/share/salor-hospitality
backupdir_database=/var/lib/salor-hospitality/backups/database
backupdir_log=/var/lib/salor-hospitality/backups/log
database_conf_file=/etc/salor-hospitality-config.yml
numversions=60
d=$(date)

# ROLL PRODUCTION LOG

mkdir -p $backupdir_log

cd $app_root/log
mv production.log 0-production.log
touch production.log
chmod 777 production.log
gzip 0-production.log
mv 0-production.log.gz $backupdir_log

cd $backupdir_log

# Rollover the backup files
i=$numversions
rm -rf $backupdir_log/$i-production.log.gz
while [ $i -gt 0 ]
do
  mv $backupdir_log/`expr $i - 1`-production.log.gz $backupdir_log/$i-production.log.gz
  i=`expr $i - 1`
done


# ROLL DATABASE

usernameline=`grep 'username:' $database_conf_file | head -1`
username=`echo $usernameline | sed -e 's/username: //'`

databaseline=`grep 'database:' $database_conf_file | head -1`
database=`echo $databaseline | sed -e 's/database: //'`

passwordline=`grep 'password:' $database_conf_file | head -1`
password=`echo $passwordline | sed -e 's/password: //'`

# The most recent backup is called 0-database_name.sql.gz
mkdir -p $backupdir_database
cd $backupdir_database
mysqldump --user $username --password=$password --opt $database > 0-$database.sql
gzip 0-$database.sql

# Rollover the backup directories
i=$numversions
rm -fr $backupdir_database/$i-$database.sql.gz
while [ $i -gt 0 ]
do
  mv $backupdir_database/`expr $i - 1`-$database.sql.gz $backupdir_database/$i-$database.sql.gz
  i=`expr $i - 1`
done

# Copy the latest backup to the Desktop
# TODO: Add check if ls /home | wc -l equals 1, so that we don't put the database to the Desktop of a different user.
mainuser=`ls /home | head -1`
cp ${backupdir_database}/1-$database.sql.gz /home/$mainuser/Desktop/salor-hospitality-database.sql.gz
chmod 666 /home/$mainuser/Desktop/salor-hospitality-database.sql.gz

exit 0
