#!/bin/bash
echo ""
echo "Testing for salor-hospitality SSL certificates for HTTPS access..."
if [ ! -f /etc/apache2/ssl/salor-hospitality.crt ]; then
  echo "salor-hospitality SSL certificates don't exist yet, creating them..."
  cd /root
  mkdir salor-hospitality_ssl_certificates
  cd salor-hospitality_ssl_certificates
  openssl req -new -newkey rsa:4096 -nodes -out salor-hospitality.csr -keyout salor-hospitality.key -subj "/C=AT/ST=/L=/O=SalorHospitality POS/CN=salor-hospitality"
  openssl req -x509 -days 6000 -in salor-hospitality.csr -key salor-hospitality.key -out salor-hospitality.crt
  chmod 600 salor-hospitality.*
  mkdir /etc/apache2/ssl
  cp salor-hospitality.key salor-hospitality.crt /etc/apache2/ssl
  echo "Enabling Apache SSL module..."
  a2enmod ssl
else
  echo "SALOR SSL certificates already exist."
fi

echo ""
if [ "$1" = "" ]
then
  echo "Using Port numbers 443 and 7652 as default. You can re-run this script and specify a different port number as first command line parameter which will be used instead of 7652. Instead, you can edit /etc/apache2/sites-available/salor-hospitality-ssl directly"
else
  echo "Writing SSL port $1 to /etc/apache2/sites-available/salor-hospitality-ssl."
  sed -i -e "s/^Listen .*$/Listen $1/" /etc/apache2/sites-available/salor-hospitality-ssl
  sed -i -e "s/^<VirtualHost .*>$/<VirtualHost *:$1>/" /etc/apache2/sites-available/salor-hospitality-ssl
  echo "Enabling Apache site /etc/apache2/sites-available/salor-hospitality-ssl"
  cd /etc/apache2/sites-enabled
  ln -sf ../sites-available/salor-hospitality-ssl salor-hospitality-ssl
fi

echo "Enabling Apache SSL module..."
a2enmod ssl
echo "Restarting Apache service..."
service apache2 restart