#!/bin/bash

# This script is run from cron once a day in order to keep the production
# log from growing too huge. It's a 60-day rolling backup. #1 is most recent,
# and #60 is from 60 days ago

# Config
backupdir=/opt/salor/hospitality/log
numversions=60
d=$(date)

echo $(date)" - Starting 60-day Salor production.log Rotate..."

# Create current backup
cd ${backupdir}
gzip production.log

# Rollover the backup files
i=$numversions
rm -f ${backupdir}/production.log.$i.gz 2> /dev/null
while [ $i -gt 0 ]
do
	mv ${backupdir}/production.log.`expr $i - 1`.gz ${backupdir}/production.log.$i.gz 2> /dev/null
	i=`expr $i - 1`
done

mv ${backupdir}/production.log.gz ${backupdir}/production.log.1.gz 2> /dev/null
touch ${backupdir}/production.log 2> /dev/null
chmod 777 ${backupdir}/production.log 2> /dev/null

echo " --> Salor production.log Rotate Complete."
exit 0
