#!/bin/bash

# This script is run from cron once a day in order to generate backups
# of the Salor DB. It's a 60-day rolling backup. #1 is most recent,
# and #60 is from 60 days ago

usernameline=`grep 'username:' /opt/salor/hospitality/config/database.yml | head -1`
username=`echo $usernameline | sed -e 's/username: //'`

databaseline=`grep 'database:' /opt/salor/hospitality/config/database.yml | head -1`
database=`echo $databaseline | sed -e 's/database: //'`

passwordline=`grep 'password:' /opt/salor/hospitality/config/database.yml | head -1`
password=`echo $passwordline | sed -e 's/password: //'`

# Config
backupdir=/opt/salor/hospitality-db-rolling-backups
numversions=60
d=$(date)

echo $(date)" - Starting 60-day Salor DB Rolling Backup..."

# Create dir if needed
mkdir -p ${backupdir}/backup.0
if [ ! -d ${backupdir} ]
then
  echo "Invalid directory: ${backupdir}"
exit 1
fi

# Create current backup
cd /var/log
mysqldump --user $username --password=$password --opt ${database} > ${database}.sql
gzip ${database}.sql
mv ${database}.sql.gz ${backupdir}/backup.0/${database}.sql.gz 2> /dev/null

# Rollover the backup directories
i=$numversions
rm -fr ${backupdir}/backup.$i 2> /dev/null
while [ $i -gt 0 ]
do
	mv ${backupdir}/backup.`expr $i - 1` ${backupdir}/backup.$i 2> /dev/null
	i=`expr $i - 1`
done

# Copy the latest backup to the Desktop
mainuser=`ls /home | head -1`
cp ${backupdir}/backup.1/${database}.sql.gz /home/$mainuser/Desktop/salor-hospitality-backup.sql.gz 2> /dev/null
chmod 666 /home/$mainuser/Desktop/salor-hospitality-backup.sql.gz 2> /dev/null

echo " --> Salor Rolling Backup Complete."
exit 0
